# -*- coding: utf-8 -*-
"""k means.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O4zdcIyFtJlUJNURa3BlFr21KTkcRVGc
"""

import numpy as np
import matplotlib.pyplot as plt

# Step 1: Create sample dataset
np.random.seed(42)
X = np.vstack((
    np.random.randn(50, 2) + [2, 2],
    np.random.randn(50, 2) + [8, 8]
))

# Step 2: K-Means Function
def kmeans(X, k, max_iters=100):

    # Randomly choose initial centroids
    indices = np.random.choice(len(X), k, replace=False)
    centroids = X[indices]

    for _ in range(max_iters):
        # Step 3: Assign clusters
        distances = np.linalg.norm(X[:, np.newaxis] - centroids, axis=2)
        labels = np.argmin(distances, axis=1)

        # Step 4: Compute new centroids
        new_centroids = np.array([X[labels == i].mean(axis=0) for i in range(k)])

        # Step 5: Check convergence
        if np.all(centroids == new_centroids):
            break

        centroids = new_centroids

    return centroids, labels


# Step 6: Run K-Means
k = 2
centroids, labels = kmeans(X, k)

# Step 7: Plot Results
plt.scatter(X[:, 0], X[:, 1], c=labels, cmap='viridis')
plt.scatter(centroids[:, 0], centroids[:, 1], c='red', marker='X', s=200)
plt.title("K-Means Clustering (From Scratch)")
plt.show()